# Numpy
`numpy` è la principale library di calcolo scientifico in Python. La feature che l'ha resa tale è l'implementazione offerta degli array multidimensionali, e delle loro operazioni.

## Esercizi
Questi esercizi ci permetteranno di familiarizzare con i fondamenti della library. Se non sei sicuro della sintassi, fai riferimento al [Numpy cheatsheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf).
### Esercizio
Importa la library e verificane la versione

In [2]:
import numpy as np

print(np.__version__)

1.20.1


### Esercizio
`numpy` è, tra le altre cose, anche un ottimo *collettore* di funzioni matematiche, quali:
* esponenziali e logaritmi
* funzioni trigonometriche
Per approfondire [link](https://numpy.org/doc/stable/reference/routines.math.html).

In [9]:
np.log10(1000)

3.0

In [10]:
np.log(np.exp(10))

10.0

In [11]:
np.sin(np.pi/2)

1.0

### Esercizio
Definisci un array monodimensionale di 5 elementi, ed assegnalo alla variabile `x`. Ispeziona poi la dimensione della variabile ottenuta.

In [17]:
x = np.array([-1, 4, 5, 3, 2])
print(x)
print(x.shape)

[-1  4  5  3  2]
(5,)


### Esercizio
Trova il massimo ed il minimo di `x`.

In [18]:
print(np.min(x), np.max(x))

-1 5


### Esercizio
Trova l'indice corrispondente al minimo ed al massimo valore di `x`.

In [19]:
print(np.argmin(x), np.argmax(x))

0 2


### Esercizio
Definisci un array bidimensionale di 10 elementi disposti in 2 righe da 5 elementi ciascuno, ed assegnalo alla variabile `A`. Ispeziona poi la dimensione della variabile ottenuta.

In [20]:
A = np.array([[5,  6, 7,   8,  9],
              [10, 11, 12, 13, 14]])
print(A)
print(A.shape)

[[ 5  6  7  8  9]
 [10 11 12 13 14]]
(2, 5)


### Esercizio
Trasponi righe e colonne dell'array dell'esercizio precedente, ed assegnalo alla variabile `AT`. Ispeziona poi la dimensione della variabile ottenuta.

In [ ]:
AT = A.T
print(AT)
print(AT.shape)

### Esercizio (bonus)
Sapresti ottenere un vettore di dimensione `(5, 1)`?

In [ ]:
xt = np.array([[0], [1], [2], [3], [4]])
print(xt)
print(xt.shape)

### Esercizio
Definisci un array di 50 elementi, tutti pari a 0.

In [ ]:
np.zeros(50)

### Esercizio
Definisci un array di 50 elementi, tutti pari a 1.

In [ ]:
np.ones(50)

### Esercizio (bonus)
Sfrutta la sintassi di `numpy` per creare facilmente degli array multidimensionali della stessa forma di `AT` (vedi *Es 4*) inzializzandone il contenuto a 0 o ad 1.

In [ ]:
print(np.zeros_like(AT))
print(np.ones_like(AT))

### Esercizio
Riempi un array multidimensionale di dimensione `(m, n)` di numeri estratti da una distribuzione normale $\mathcal{N}(0,1)$, ed assegnalo alla variabile `X`.

In [ ]:
m = 5
n = 3
X = np.random.randn(m, n)
X

### Esercizio
Crea un array di `n` elementi crescenti: $0, \dots, n$ (passo 1).

In [ ]:
np.arange(10)

### Esercizio
Crea un array di `n` elementi equispaziati linearmente tra 1 e 10 (prova per diversi valori di `n`). Per approfondire: [link](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html).

In [ ]:
np.linspace(1, 10, 5)

## BONUS - Linear Algebra

### Esercizio
Definisci un vettore `v` di dimensione `(n)` e calcola il prodotto matrice-vettore $X \cdot v$. Per approfondire: [link](https://numpy.org/doc/stable/reference/generated/numpy.dot.html).

In [ ]:
v = np.array([0, 0, 1])
X.dot(v)

### Esercizio
Definisci un vettore `w` di dimensione `(n, 1)` e calcola il prodotto matrice-vettore $X \cdot w$. Cosa cambia? Per approfondire: [link](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html).

In [ ]:
w = v.reshape(-1, 1)
X.dot(w)

### Esercizio
Definisci due vettori monodimensionali (di dimensioni a piacere). Calcola il loro vettore somma ed il loro vettore differenza.

In [ ]:
a = np.random.randn(5)
b = np.random.randn(5)
print(a + b)

### Esercizio
Sfruttando un array multidimensionale, definisci due matrici di dimensione a piacere, e calcolane il relativo [prodotto element-wise](https://en.wikipedia.org/wiki/Hadamard_product_(matrices)).

In [ ]:
np.random.randn(5, 5) * np.random.randn(5, 5)

### Esercizio
Sfruttando un array multidimensionale, definisci una (piccola) matrice invertibile `X` e calcolane l'inversa. Per approfondire: [link](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html).

In [ ]:
X = np.random.randn(5, 5)
X = X.T.dot(X)
np.linalg.inv(X)

### Esercizio (bonus)
Sfrutta quanto hai imparato fino a questo momento per risolvere il seguente sistema di equazioni lineari:
\begin{cases} 3x + 2y - z = 1 \\ 2x – 2y + 4z = -2 \\ -x + \frac{1}{2}y - 1z = 0 \end{cases}

In [ ]:
A = np.array([[3, 2, -1],
              [2, -2, 4],
              [-1, .5, -1]])
b = np.array([1, -2, 0])
np.linalg.inv(A).dot(b)

### Esercizio (bonus)
Ripeti quanto sopra ma prova a variare il passo.

In [ ]:
np.arange(0, 10, 3)

### Esercizio (bonus)
Crea un array di `n` elementi equispaziati logaritmicamente tra 0 e 10 (prova per diversi valori di `n`). Per approfondire: [link](https://numpy.org/doc/stable/reference/generated/numpy.logspace.html).

In [ ]:
np.logspace(0, 1, 5)

### Esercizio
Crea un array multidimensionale di dimensione `(4, 3)`. Estrai il terzo elemento della seconda riga.

In [ ]:
A = np.random.randn(4, 3)
print(A)
print(A[1,2])

### Esercizio
Crea un array multidimensionale di dimensione `(m, n)`. Estraine la prima e l'ultima colonna.

In [ ]:
A = np.random.randn(5, 5)
print(A)
print(A[:, 0])
print(A[:, -1])

### Esercizio
Crea un array multidimensionale di dimensione `(3, 4)`. Elimina le ultime due colonne.

In [ ]:
A = np.random.randn(3, 4)
print(A)
print(A[:, :-2])

### Esercizio
Nell'array dell'esercizio 17, tieni solo la prima e la terza colonna.

In [ ]:
print(A[:, 0::2])

### Esercizio
Dall'array dell'esercizio 17, ottieni un secondo array uguale al primo, ma con la prima e l'ultima riga scambiate di posizione.

In [ ]:
A[:, [-1, 1, 2, 0]]

### Esercizio
Altra particolarità di `numpy` è la possibilità di selezionare alcuni elementi di un array multidimensionale una maschera di `bool`. Prova ad esempio a selezionare i valori di `A` maggiori di 7.

In [24]:
A[A > 7]

array([ 8,  9, 10, 11, 12, 13, 14])

### Esercizio
Crea due vettori multidimensionali di dimensione `(m, n)` e concatenali prima verticalmente, poi orizzontalmente. Per approfondire: [link](https://numpy.org/doc/stable/reference/generated/numpy.stack.html).

In [ ]:
A = np.random.randn(3, 2)
B = np.random.randn(3, 2)

print(np.vstack([A, B]))
print(np.hstack([A, B]))

### Esercizio
Crea un array di `n` elementi. Calcolane poi media, varianza, deviazione standard e mediana.

In [ ]:
x = np.random.randn(10)
print(np.mean(x), np.var(x), np.std(x), np.median(x))

### Esercizio
Crea un vettore di 100 elementi casuali estratti da una distribuzione discreta uniforme $~U(0,256)$ ed ordinali in maniera crescente. Per approfondire: [link](https://numpy.org/doc/stable/reference/random/index.html?highlight=random#module-numpy.random).

In [ ]:
np.sort(np.random.randint(0, 256, 100))