# Numpy
`numpy` è la principale library di calcolo scientifico in Python. La feature che l'ha resa tale è l'implementazione offerta degli array multidimensionali, e delle loro operazioni.

## Esercizi
Questi esercizi ci permetteranno di familiarizzare con i fondamenti della library. Se non sei sicuro della sintassi, fai riferimento al [Numpy cheatsheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf).
### Esercizio
Importa la library e verificane la versione

In [ ]:
import numpy as np

print(np.__version__)

### Esercizio
`numpy` è, tra le altre cose, anche un ottimo *collettore* di funzioni matematiche, quali:
* esponenziali e logaritmi
* funzioni trigonometriche
Per approfondire [link](https://numpy.org/doc/stable/reference/routines.math.html).

In [ ]:
np.log10(1000)

In [ ]:
np.log(np.exp(10))

In [ ]:
np.sin(np.pi/2)

### Esercizio
Definisci un array monodimensionale di 5 elementi, ed assegnalo alla variabile `x`. Ispeziona poi la dimensione della variabile ottenuta.

In [ ]:
x = np.array([-1, 4, 5, 3, 2])
print(x)
print(x.shape)

### Esercizio
Trova il massimo ed il minimo di `x`.

In [ ]:
print(np.min(x), np.max(x))

### Esercizio
Trova l'indice corrispondente al minimo ed al massimo valore di `x`.

In [ ]:
print(np.argmin(x), np.argmax(x))

### Esercizio
Definisci un array bidimensionale di 10 elementi disposti in 2 righe da 5 elementi ciascuno, ed assegnalo alla variabile `A`. Ispeziona poi la dimensione della variabile ottenuta.

In [ ]:
A = np.array([[5,  6, 7,   8,  9],
              [10, 11, 12, 13, 14]])
print(A)
print(A.shape)

### Esercizio
Trasponi righe e colonne dell'array dell'esercizio precedente, ed assegnalo alla variabile `AT`. Ispeziona poi la dimensione della variabile ottenuta.

In [ ]:
AT = A.T
print(AT)
print(AT.shape)

### Esercizio (bonus)
Sapresti ottenere un vettore di dimensione `(5, 1)`?

In [ ]:
xt = np.array([[0], [1], [2], [3], [4]])
print(xt)
print(xt.shape)

### Esercizio
Definisci un array di 50 elementi, tutti pari a 0.

In [ ]:
np.zeros(50)

### Esercizio
Definisci un array di 50 elementi, tutti pari a 1.

In [ ]:
np.ones(50)

### Esercizio (bonus)
Sfrutta la sintassi di `numpy` per creare facilmente degli array multidimensionali della stessa forma di `AT` (vedi *Es 4*) inzializzandone il contenuto a 0 o ad 1.

In [ ]:
print(np.zeros_like(AT))
print(np.ones_like(AT))

### Esercizio
Riempi un array multidimensionale di dimensione `(m, n)` di numeri estratti da una distribuzione normale $\mathcal{N}(0,1)$, ed assegnalo alla variabile `X`.

In [ ]:
m = 5
n = 3
X = np.random.randn(m, n)
X

### Esercizio
Crea un array di `n` elementi crescenti: $0, \dots, n$ (passo 1).

In [ ]:
np.arange(10)

### Esercizio
Crea un array di `n` elementi equispaziati linearmente tra 1 e 10 (prova per diversi valori di `n`). Per approfondire: [link](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html).

In [16]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

## BONUS - Linear Algebra

### Esercizio
Definisci un vettore `v` di dimensione `(n)` e calcola il prodotto matrice-vettore $X \cdot v$. Per approfondire: [link](https://numpy.org/doc/stable/reference/generated/numpy.dot.html).

In [17]:
v = np.array([0, 0, 1])
X.dot(v)

array([ 0.11288224,  0.9204381 ,  0.9944162 , -0.91218724,  1.34944048])

### Esercizio
Definisci un vettore `w` di dimensione `(n, 1)` e calcola il prodotto matrice-vettore $X \cdot w$. Cosa cambia? Per approfondire: [link](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html).

In [18]:
w = v.reshape(-1, 1)
X.dot(w)

array([[ 0.11288224],
       [ 0.9204381 ],
       [ 0.9944162 ],
       [-0.91218724],
       [ 1.34944048]])

### Esercizio
Definisci due vettori monodimensionali (di dimensioni a piacere). Calcola il loro vettore somma ed il loro vettore differenza.

In [19]:
a = np.random.randn(5)
b = np.random.randn(5)
print(a + b)

[ 1.71646921 -2.27636637 -3.59961787  3.08187312 -0.02613455]


### Esercizio
Sfruttando un array multidimensionale, definisci due matrici di dimensione a piacere, e calcolane il relativo [prodotto element-wise](https://en.wikipedia.org/wiki/Hadamard_product_(matrices)).

In [20]:
np.random.randn(5, 5) * np.random.randn(5, 5)

array([[ 0.22064609,  0.04363637, -0.01535257, -0.5088212 ,  3.91723697],
       [-0.1579679 ,  0.14691091, -0.271532  ,  1.14846825,  0.76679999],
       [-0.15748109, -0.29200173, -0.35839673, -0.28220988,  3.51206426],
       [ 1.65177051, -0.24656386,  0.25563383, -0.02150756, -0.13834135],
       [-0.99379887,  0.02993616, -0.11540498,  0.71271665,  1.14534206]])

### Esercizio
Sfruttando un array multidimensionale, definisci una (piccola) matrice invertibile `X` e calcolane l'inversa. Per approfondire: [link](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html).

In [21]:
X = np.random.randn(5, 5)
X = X.T.dot(X)
np.linalg.inv(X)

array([[ 2.28113943, -1.58638064,  1.89165681,  2.76270424,  0.68132478],
       [-1.58638064,  2.13008057, -1.88096716, -3.89855027, -0.99403838],
       [ 1.89165681, -1.88096716,  2.13663334,  3.74180853,  0.99970896],
       [ 2.76270424, -3.89855027,  3.74180853,  8.12328382,  2.03351442],
       [ 0.68132478, -0.99403838,  0.99970896,  2.03351442,  0.72036316]])

### Esercizio (bonus)
Sfrutta quanto hai imparato fino a questo momento per risolvere il seguente sistema di equazioni lineari:
\begin{cases} 3x + 2y - z = 1 \\ 2x – 2y + 4z = -2 \\ -x + \frac{1}{2}y - 1z = 0 \end{cases}

In [22]:
A = np.array([[3, 2, -1],
              [2, -2, 4],
              [-1, .5, -1]])
b = np.array([1, -2, 0])
np.linalg.inv(A).dot(b)

array([ 1., -2., -2.])

### Esercizio (bonus)
Ripeti quanto sopra ma prova a variare il passo.

In [23]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

### Esercizio (bonus)
Crea un array di `n` elementi equispaziati logaritmicamente tra 0 e 10 (prova per diversi valori di `n`). Per approfondire: [link](https://numpy.org/doc/stable/reference/generated/numpy.logspace.html).

In [24]:
np.logspace(0, 1, 5)

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

### Esercizio
Crea un array multidimensionale di dimensione `(4, 3)`. Estrai il terzo elemento della seconda riga.

In [25]:
A = np.random.randn(4, 3)
print(A)
print(A[1,2])

[[ 0.11012691  2.28397805  0.82639427]
 [ 0.29566736 -1.36754451 -0.73064513]
 [-1.53090029  0.12993072  1.9937656 ]
 [ 0.55017522  0.15263776 -0.7855201 ]]
-0.7306451342116969


### Esercizio
Crea un array multidimensionale di dimensione `(m, n)`. Estraine la prima e l'ultima colonna.

In [26]:
A = np.random.randn(5, 5)
print(A)
print(A[:, 0])
print(A[:, -1])

[[-0.33588167 -0.95248707 -0.36985291 -1.16747433  0.643861  ]
 [ 0.41280823  0.29913222  0.17774678 -0.17959601  0.79963754]
 [ 0.3249601   0.09802323 -2.16437413  0.95932042  1.87178199]
 [-0.43266171  1.00420837 -1.14877208  0.39134011  1.56908885]
 [-0.20473177 -1.96718382  0.68980217 -0.15319981 -0.83920068]]
[-0.33588167  0.41280823  0.3249601  -0.43266171 -0.20473177]
[ 0.643861    0.79963754  1.87178199  1.56908885 -0.83920068]


### Esercizio
Crea un array multidimensionale di dimensione `(3, 4)`. Elimina le ultime due colonne.

In [27]:
A = np.random.randn(3, 4)
print(A)
print(A[:, :-2])

[[ 0.9730375  -0.18998417  1.96022231  0.38513592]
 [-1.50254348  1.31656419 -0.18753828  1.76539165]
 [-0.86302095 -0.07664522  0.08125348 -0.84060611]]
[[ 0.9730375  -0.18998417]
 [-1.50254348  1.31656419]
 [-0.86302095 -0.07664522]]


### Esercizio
Nell'array dell'esercizio 17, tieni solo la prima e la terza colonna.

In [28]:
print(A[:, 0::2])

[[ 0.9730375   1.96022231]
 [-1.50254348 -0.18753828]
 [-0.86302095  0.08125348]]


### Esercizio
Dall'array dell'esercizio 17, ottieni un secondo array uguale al primo, ma con la prima e l'ultima riga scambiate di posizione.

In [29]:
A[:, [-1, 1, 2, 0]]

array([[ 0.38513592, -0.18998417,  1.96022231,  0.9730375 ],
       [ 1.76539165,  1.31656419, -0.18753828, -1.50254348],
       [-0.84060611, -0.07664522,  0.08125348, -0.86302095]])

### Esercizio
Altra particolarità di `numpy` è la possibilità di selezionare alcuni elementi di un array multidimensionale una maschera di `bool`. Prova ad esempio a selezionare i valori di `A` maggiori di 7.

In [30]:
A[A > 7]

array([], dtype=float64)

### Esercizio
Crea due vettori multidimensionali di dimensione `(m, n)` e concatenali prima verticalmente, poi orizzontalmente. Per approfondire: [link](https://numpy.org/doc/stable/reference/generated/numpy.stack.html).

In [31]:
A = np.random.randn(3, 2)
B = np.random.randn(3, 2)

print(np.vstack([A, B]))
print(np.hstack([A, B]))

[[-0.35064528 -1.73558781]
 [ 0.01382243  1.8416894 ]
 [ 0.66356539  0.17440429]
 [ 1.51840411  2.24849832]
 [-1.20004509 -0.16221581]
 [ 0.14652701  0.43189229]]
[[-0.35064528 -1.73558781  1.51840411  2.24849832]
 [ 0.01382243  1.8416894  -1.20004509 -0.16221581]
 [ 0.66356539  0.17440429  0.14652701  0.43189229]]


### Esercizio
Crea un array di `n` elementi. Calcolane poi media, varianza, deviazione standard e mediana.

In [32]:
x = np.random.randn(10)
print(np.mean(x), np.var(x), np.std(x), np.median(x))

0.25899648811509757 0.4377304279088766 0.6616119919627188 0.19809448781436684


### Esercizio
Crea un vettore di 100 elementi casuali estratti da una distribuzione discreta uniforme $~U(0,256)$ ed ordinali in maniera crescente. Per approfondire: [link](https://numpy.org/doc/stable/reference/random/index.html?highlight=random#module-numpy.random).

In [33]:
np.sort(np.random.randint(0, 256, 100))

array([  5,   6,   7,   9,  17,  19,  23,  33,  34,  35,  36,  37,  39,
        41,  42,  47,  53,  54,  56,  56,  63,  64,  64,  66,  67,  67,
        70,  76,  76,  77,  83,  87,  90,  91,  93,  97,  98, 100, 100,
       103, 107, 109, 111, 116, 122, 123, 126, 130, 134, 143, 145, 146,
       148, 151, 156, 163, 163, 163, 163, 165, 169, 171, 171, 171, 174,
       174, 180, 184, 185, 186, 186, 187, 191, 196, 197, 199, 200, 204,
       204, 206, 208, 210, 212, 214, 218, 223, 224, 236, 237, 237, 242,
       244, 246, 248, 249, 250, 251, 253, 254, 254])